language: php
php:
    - 5.6
    - 5.5
#    - hhvm

before_script:
    - sh -c "if [ "$TRAVIS_PHP_VERSION" != 'hhvm' ]; then pecl config-set preferred_state beta; yes '' | pecl install apcu; fi;"
    - sh -c 'echo apc.enabled=1 >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini'
    - sh -c 'echo apc.enable_cli=1 >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini'
    - composer selfupdate
    - composer install --prefer-source
#    - sh -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then echo "hhvm.libxml.ext_entity_whitelist = file,http"  >> /etc/hhvm/php.ini; fi;'

script: ./bin/phpunit -c app/
