language: php
php:
    - 5.6
    - 5.5
#    - hhvm

before_script:
    - sh -c "if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]] ; then pecl config-set preferred_state beta; printf "yes\n" | pecl install apcu; fi;"
    - composer selfupdate
    - composer install --prefer-source
#    - sh -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then echo "hhvm.libxml.ext_entity_whitelist = file,http"  >> /etc/hhvm/php.ini; fi;'

script: ./bin/phpunit -c app/
