imports:
    - { resource: config.yml }

monolog:
    handlers:
#        main:
#            type:         fingers_crossed
#            action_level: error
#            handler:      nested
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
        console:
            type:  console

services:
    hrom.cache:
        class: Doctrine\Common\Cache\ApcuCache
