imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['php']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

mcfedr_aws_push:
    platforms: "%push_platforms%"
    topic_arn: "%push_topic%"
    aws:
        key: "%push_aws_key%"
        secret: "%push_aws_secret%"
        region: "%push_aws_region%"

mcfedr_twitter_push:
    twitter:
        consumer_key: "%twitter_consumer_key%"
        consumer_secret: "%twitter_consumer_secret%"
        token: "%twitter_token%"
        token_secret: "%twitter_token_secret%"
    userid: "%twitter_userid%"
    max_pushes_per_hour: "%twitter_max_pushes_per_hour%"
    cache: hrom.cache

mcfedr_you_tube_live_streams:
    api_key: "%youtube_api_key%"
    channel_id: "%youtube_channel_id%"
    cache: "hrom.cache"
    cache_timeout: "%cache_timeout%"

mcfedr_hromadske_api:
    radio: "%hromadske_radio%"

mcfedr_hromadske_news:
    homepage: "%hromadske_homepage%"
    cache: "hrom.cache"
    cache_timeout: "%cache_timeout%"

services:
    hrom.cache:
        class: Doctrine\Common\Cache\ArrayCache
