mcfedr_hromadske_news:
    resource: "@mcfedrHromadskeNewsBundle/Controller/"
    type:     annotation
    prefix:   /

mcfedr_hromadske_api:
    resource: "@mcfedrHromadskeApiBundle/Controller/"
    type:     annotation
    prefix:   /

mcfedr_aws_push:
    resource: "@mcfedrAWSPushBundle/Controller/"
    type:     annotation
    prefix:   /
