mcfedr_hromadske_api:
    resource: "@McfedrHromadskeApiBundle/Controller/"
    type:     annotation
    prefix:   /

mcfedr_aws_push:
    resource: "@McfedrAwsPushBundle/Controller/"
    type:     annotation
    prefix:   /
