security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER, ROLE_MCFEDR_AWS_BROADCAST
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: "%admin_password%", roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        broadcast:
            pattern:  ^/broadcast
            stateless: true
            http_basic: ~

    access_control:
        - { path: ^/broadcast, roles: ROLE_MCFEDR_AWS_BROADCAST }
